#!/usr/local/bin/bash

URLS=( [Clippers]="http://www.oddsshark.com/stats/gamelog/basketball/nba/20736"
       [Knicks]="http://www.oddsshark.com/stats/gamelog/basketball/nba/20747"
       [Nets]="http://www.oddsshark.com/stats/gamelog/basketball/nba/20749"
       [Sixers]="http://www.oddsshark.com/stats/gamelog/basketball/nba/20731"
       [Celtics]="http://www.oddsshark.com/stats/gamelog/basketball/nba/20722"
       [Raptors]="http://www.oddsshark.com/stats/gamelog/basketball/nba/20742"
       [Pistons]="http://www.oddsshark.com/stats/gamelog/basketball/nba/20743"
       [Pacers]="http://www.oddsshark.com/stats/gamelog/basketball/nba/20737"
       [Cavaliers]="http://www.oddsshark.com/stats/gamelog/basketball/nba/20735"
       [Bulls]="http://www.oddsshark.com/stats/gamelog/basketball/nba/20732"
       [Bucks]="http://www.oddsshark.com/stats/gamelog/basketball/nba/20725"
       [Wizards]="http://www.oddsshark.com/stats/gamelog/basketball/nba/20746"
       [Miami]="http://www.oddsshark.com/stats/gamelog/basketball/nba/20726"
       [Bobcats]="http://www.oddsshark.com/stats/gamelog/basketball/nba/20751"
       [Magic]="http://www.oddsshark.com/stats/gamelog/basketball/nba/20750"
       [Hawks]="http://www.oddsshark.com/stats/gamelog/basketball/nba/20734"
       [Nuggets]="http://www.oddsshark.com/stats/gamelog/basketball/nba/20723"
       [Timberwolves]="http://www.oddsshark.com/stats/gamelog/basketball/nba/20744"
       [Jazz]="http://www.oddsshark.com/stats/gamelog/basketball/nba/20738"
       [Blazers]="http://www.oddsshark.com/stats/gamelog/basketball/nba/20748"
       [Thunder]="http://www.oddsshark.com/stats/gamelog/basketball/nba/20728"
       [Kings]="http://www.oddsshark.com/stats/gamelog/basketball/nba/20745"
       [Suns]="http://www.oddsshark.com/stats/gamelog/basketball/nba/20730"
       [Warriors]="http://www.oddsshark.com/stats/gamelog/basketball/nba/20741"
       [Spurs]="http://www.oddsshark.com/stats/gamelog/basketball/nba/20724"
       [Mavericks]="http://www.oddsshark.com/stats/gamelog/basketball/nba/20727"
       [Pelicans]="http://www.oddsshark.com/stats/gamelog/basketball/nba/20733"
       [Rockets]="http://www.oddsshark.com/stats/gamelog/basketball/nba/20740"
       [Grizzles]="http://www.oddsshark.com/stats/gamelog/basketball/nba/20729"
  )

TEAMS=( [Clippers]="LA Clippers"
        [Knicks]="New York"
        [Nets]="New Jersey"
        [Sixers]="Philadelphia"
        [Celtics]="Boston"
        [Raptors]="Toronto"
        [Pistons]="Detoit"
        [Pacers]="Indiana"
        [Cavaliers]="Cleveland"
        [Bulls]="Chicago"
        [Bucks]="Milwaukee"
        [Wizards]="Washington"
        [Heat]="Miami"
        [Bobcats]="Charlotte"
        [Magic]="Orlando"
        [Hawks]="Atlanta"
        [Nuggets]="Denver"
        [Timberwolves]="Minnesota"
        [Jazz]="Utah"
        [Blazers]="Portland"
        [Suns]="Phoenix"
        [Kings]="Sacramento"
        [Thunder]="Oklahoma City"
        [Warriors]="Golden State"
        [Spurs]="San Antonio"
        [Lakers]="LA Lakers"
        [Mavericks]="Dallas"
        [Pelicans]="New Orleans"
        [Rockets]="Houston"
        [Grizzlies]="Memphis"
  )

curl --include --request POST localhost:3000/scrape \
  --header "Content-Type: application/json" \
  --data '{
    "url": "http://www.oddsshark.com/stats/gamelog/basketball/nba/20740/2017",
    "team" : "Houston"
  }'